- CMakeLists.txt
- cmake/Modules/GaloisConfig.cmake.in
- libgalois/CMakeLists.txt
This should make it so that the headers and library install fine.
> Installation Fixes

- .circleci/config.yml
Some of the third party package ABIs have changed since I set the original CircleCI builds up. This is aimed primarily at sorting that out, though I will throw in some other small fixes as well.
Experimentation in progress.
> WIP: Fix Various CircleCI builds

- .circleci/config.yml
- .travis.yml
- lonestar/matrixcompletion/CMakeLists.txt
Disable the tests requiring Eigen if it isn't found.
Also install Eigen in a few of the CI runs.
> Fix Eigen/CI test interaction

- .travis.yml
- lonestar/pointstoanalysis/CMakeLists.txt
Trying this out. The crashes with gmetis should probably be fixed before this actually gets merged.
> Run test on Travis CI as well.

- inputs/CMakeLists.txt
Make the CMake stuff for downloading the new sample inputs actually work.
> Download fix

- .circleci/config.yml
- .travis.yml
- CMakeLists.txt
- README.md
- inputs/CMakeLists.txt
This should make it easier for people to download Galois and test that it's working. It also improves the documentation for how to download and test everything.
> Cmake Input Downloading and Testing

- .travis.yml
> Test gcc 9 in Travis CI

- README.md
> (nit) README: graph-convert and meminfo fixes

- .circleci/config.yml
Debugging in progress. Will merge when finished.
> Fix Debian CI failure

- .travis.yml
- CMakeLists.txt
- libgalois/include/galois/DynamicBitset.h
- libgalois/include/galois/graphs/LC_CSR_Graph.h
- libgalois/include/galois/graphs/MorphGraph.h
- libgluon/include/galois/graphs/GluonEdgeSubstrate.h
- libgluon/include/galois/graphs/GluonSubstrate.h
- lonestar/delaunaytriangulation/DelaunayTriangulationDet.cpp
- lonestar/sssp/SSSP.cpp
- lonestar/tutorial_examples/ConflictAwareTorus.cpp
- test/papi.cpp
I didn't realize that `-DENABLE_DIST_GALOIS=ON` was a standard option 🤷‍♂.
This should be the rest of the necessary changes for *building*. There needs to be some more work to fix running on MacOS as the system introspection interface is different (e.g., no procfs).
> Rest of the MacOS fixes

- libgalois/include/galois/graphs/OfflineGraph.h
- libgalois/src/HWTopoLinux.cpp
- libgluon/include/galois/graphs/GluonSubstrate.h
- lonestar/barneshut/Barneshut.cpp
- lonestar/betweennesscentrality/BetweennessCentralityLevel.cpp
- lonestar/delaunaytriangulation/DelaunayTriangulation.cpp
- lonestar/delaunaytriangulation/DelaunayTriangulationDet.cpp
- lonestar/matching/bipartite-mcm.cpp
- lonestar/matrixcompletion/matrixCompletion.cpp
- lonestar/matrixcompletion/matrixCompletion.h
- lonestar/pagerank/PageRank-pull.cpp
- lonestar/triangles/Triangles_AOS.cpp
- lonestardist/bc/bc_level.cpp
- lonestardist/partition/partition.cpp
- test/floatingPointErrors.cpp
- test/worklists-compile.cpp
- tools/dist-graph-convert/dist-graph-convert-helpers.cpp
- tools/dist-graph-convert/dist-graph-convert-helpers.h
- tools/dist-graph-convert/dist-graph-convert.cpp
- tools/graph-convert/graph-convert.cpp
With #58, this series of commits gets me to warning-free for
```
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_DIST_GALOIS=ON
```
on my machine at least.
> Fix compiler warnings

- lonestar/tutorial_examples/TorusImproved.cpp
- lonestardist/bc/bc_mr.cpp
- lonestardist/sgd/sgd.cpp
- test/barriers.cpp
- tools/dist-graph-convert/dist-graph-convert.cpp
And along the way delete out of date comments.
> Cleanup more unused variables

- .circleci/config.yml
- .travis.yml
- CMakeLists.txt
- README.md
This is a continuation of https://github.com/IntelligentSoftwareSystems/Galois/pull/73. See https://github.com/TRIQS/triqs/issues/523 for more details on the fix I'm using for the two libc++ Travis CI builds.
> Enable C++17

- lonestardist/CMakeLists.txt
- lonestardist/tc/tc_cuda.cu
Replaced the older moderngpu function calls with new ones. I have tested locally and verified the correctness.  
Closes #148
> fixing dist tc compilation error due to moderngpu

- lonestar/kcore/kcore.cpp
Contents are the same with the title.
> Clean comments, alignments, and indentations (through clang-format) of the kcore

- lonestar/pagerank/PageRank-constants.h
- lonestar/pagerank/PageRank-pull.cpp
- lonestar/pagerank/PageRank-push.cpp
Possible todo: we can add transposeGraph option like the symmetricGraph option.
> Apply clang-format, and doxygen comment style

- lonestar/eda/cpu/aigRewriting/CMakeLists.txt
- lonestar/eda/cpu/aigRewriting/algorithms/RewriteManager.cpp
This fixes a bug I accidentally introduced during earlier refactoring.
> Fix Crash in aigRewriting

- lonestar/eda/cpu/SPRoute/CMakeLists.txt
- lonestar/eda/cpu/SPRoute/DataProc.h
- lonestar/eda/cpu/SPRoute/bookshelf_IO.c
- lonestar/eda/cpu/SPRoute/flute.h
@Michael-JY-He has already cleared away all the warnings in SPRoute, so this just re-enables `-Werror` for that app. After this, the only thing remaining for https://github.com/IntelligentSoftwareSystems/Galois/issues/86 is the webpage.
> Enforce no warnings in SPRoute.

- libgalois/include/galois/runtime/Mem.h
- lonestar/analytics/cpu/pointstoanalysis/CMakeLists.txt
- lonestar/analytics/cpu/pointstoanalysis/PointsTo.cpp
- lonestar/analytics/cpu/pointstoanalysis/SparseBitVector.h
> adding pta test

- scripts/galois_log_parser_minimal.R
Log parsing scripts for shared-memory and distributed logs with the minimal but necessary counter.
> Add Parsing Scripts With Necessary Functionality

- lonestar/analytics/distributed/bc/bc_level.cpp
- lonestar/analytics/distributed/bc/bc_mr.cpp
Updating bc_level and bc_mr timer names to make them easy to parse.
> Update Timer Names For Parsing

- lonestar/analytics/cpu/bfs/bfs.cpp
Removing unnecessary 2 phase algorithms for Bfs.
> Remove Bfs Sync 2 Phase Algorithms

- lonestar/analytics/cpu/bipart/CMakeLists.txt
WIP: Working to isolate the latest crash here.
> Re-enable bipart tests in CI.

- libgalois/include/galois/graphs/LC_CSR_CSC_Graph.h
- lonestar/analytics/cpu/betweennesscentrality/BetweennessCentralityAsync.cpp
- lonestar/analytics/cpu/bfs/bfsDirectionOpt.cpp
Renaming B_LC_CSR_Graph something more intuitive.
> b_lc_csr -> lc_csr_csc graph

- lonestar/analytics/cpu/matrixcompletion/CMakeLists.txt
- lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp
> Matrix completion sgd block jump memory leaks

- lonestar/analytics/distributed/README.md
Updating the distributed readme with the sync/async options, performance considerations, and related publications.
> dist readme update with performance, publications

- lonestar/analytics/cpu/matching/bipartite-mcm.cpp
- lonestar/analytics/cpu/preflowpush/Preflowpush.cpp
- lonestar/eda/cpu/SPRoute/maze_finegrain.h
- lonestar/eda/cpu/SPRoute/maze_finegrain_lateupdate.h
Fixes https://github.com/IntelligentSoftwareSystems/Galois/issues/185. It turned out that just zero initializing the variables it was complaining about made the error go away.
> Work around bug in gcc 7.1 and 7.2

- lonestar/analytics/distributed/tc/tc.cpp
The CPU TC test cases failed because the personality was missing. I fixed it now. @insertinterestingnamehere  please merge when you are fine.
> fixing tc personality issue

- docs/parallel_loops.dox
- docs/tutorial.dox
- libgalois/include/galois/ParallelSTL.h
- libgalois/include/galois/Traits.h
- libgalois/include/galois/runtime/Executor_Deterministic.h
- libgalois/include/galois/runtime/Executor_ForEach.h
- libgalois/include/galois/runtime/Executor_ParaMeter.h
- libgalois/test/loop-overhead.cpp
- lonestar/analytics/cpu/betweennesscentrality/BetweennessCentralityAsync.cpp
- lonestar/analytics/cpu/bfs/bfs.cpp
- lonestar/analytics/cpu/bfs/bfsDirectionOpt.cpp
- lonestar/analytics/cpu/connectedcomponents/ConnectedComponents.cpp
- lonestar/analytics/cpu/kcore/kcore.cpp
- lonestar/analytics/cpu/ktruss/K-Truss.cpp
- lonestar/analytics/cpu/pagerank/PageRank-push.cpp
- lonestar/analytics/cpu/pointstoanalysis/PointsTo.cpp
- lonestar/analytics/cpu/preflowpush/Preflowpush.cpp
- lonestar/analytics/cpu/sssp/SSSP.cpp
- lonestar/scientific/cpu/barneshut/Barneshut.cpp
- lonestar/tutorial_examples/ExampleWrappedWorklist.cpp
- lonestar/tutorial_examples/GraphTraversalPushOperator.cpp
- lonestar/tutorial_examples/SpanningTree.cpp
- lonestar/tutorial_examples/Torus.cpp
- python/galois/cpp/libgalois/Galois.pxd
- python/galois/shmem.pxd
> no_conflicts -> disable_conflict_detection

- lonestar/analytics/cpu/betweennesscentrality/BetweennessCentralityOuter.cpp
- lonestar/analytics/cpu/betweennesscentrality/CMakeLists.txt
Adds a test for bc-level and bc-async.
Note this will likely conflict with the huge renaming change, so I will not merge until after that is done and I reconcile any naming differences.
> run test for bc-level and bc-async

- lonestar/analytics/distributed/README.md
- lonestar/analytics/gpu/README.md
- lonestar/scientific/gpu/README.md
- lonestar/scientific/gpu/barneshut/bh.cu
ModernGPU branch is updated to use master branch.
> modergpu switched to master branch to for cuda capability >= 7.0

- lonestar/eda/cpu/aig-rewriting/README.md
- lonestar/eda/cpu/sproute/README.md
I updated the README files in the eda directory
> updated README (eda)

- lonestar/mining/README.md
Match new naming and command-line argument structure.
> Update lonestar/mining README

- lonestar/scientific/cpu/longestedge/README.md
@insertinterestingnamehere 
Yesterday was a holiday in Poland and I didn't see your pull request. I suppose it should be .poly, not .mesh.
> Fix to LongestEdge readme

- lonestar/analytics/distributed/triangle-counting/README.md
Fixed the readme according to @chenxuhao comments.
> updating distTC readme

- lonestar/analytics/cpu/triangle-counting/Triangles.cpp
Switching File->BufferedGraph to separate file reading from relabeling time rather than having them interleaved.
> triangles relabel timers, switch to bufferedgraph

- libgalois/include/galois/graphs/FileGraph.h
- libgalois/src/FileGraph.cpp
- lonestar/analytics/cpu/betweennesscentrality/AsyncStructs.h
- lonestar/analytics/cpu/betweennesscentrality/BetweennessCentrality.cpp
- Made bc async use filegraph for reading like the other 2 variants
- added a degree interface for file graph for use in graph analysis before execution
In retrospect this should have been 2 different PRs.
> Consistent graph reading bc, degree interface for file graph

- lonestar/analytics/cpu/pagerank/PageRank-pull.cpp
GAP (http://gap.cs.berkeley.edu/) is considered standard for analytics.
> Change pagerank updation rule to match GAP

- libgalois/include/galois/worklists/AdaptiveObim.h
- libgalois/include/galois/worklists/WorkList.h
Fixes https://github.com/IntelligentSoftwareSystems/Galois/issues/78.
Very much still a work in progress. A relatively major overhaul is needed to get this up-to-date since the original PMOD scheduler was written against Galois 2.2.1 and so much has changed since then.
> Port Adaptive OBIM (PMOD) to Latest Galois

- lonestar/analytics/cpu/triangle-counting/Triangles.cpp
This PR adds the functionality to handle self edges in shared memory triangle counting app.
> Add functionality to handle self edges in shared memory triangle counting app

- lonestar/analytics/cpu/triangle-counting/Triangles.cpp
This PR adds the support for multi edges for triangle counting app.
> Add Multi edge support for tc
