IntelligentSoftwareSystems/Galois

.circleci/config.yml, .travis.yml
(first try it both ways to see if either setup currently works)
The CI servers recently changed their list of approved PPA repos for their APT plugin, so we'll likely have to find a different way to get CMake 3 on their ubuntu trusty image.
I'm currently experimenting with that here.
=> Fix CMake Source for CI tests

lonestar/tutorial_examples/ExampleWrappedWorklist.cpp
Older versions of GCC fail with
[...]ExampleWrappedWorklist.cpp:49:20: error: cannot call member function ‘void ExampleWrappedWorklist::enqueue(int)’ without object
enqueue(item + item);
Also, fix up some signed/unsigned warnings along the way.
=> fix capture of object in examples for GCC <= 6

libgalois/include/galois/graphs/B_LC_CSR_Graph.h, lonestar/betweennesscentrality/BetweennessCentralityAsync.cpp, lonestar/betweennesscentrality/BetweennessCentralityLevel.cpp, lonestar/kcore/kcore.cpp
Although the final widths may be the same, on some platforms, size_t and
uint64_t are not interchangable because they have different nominal
types (e.g., unsigned long long versus unsigned long) and vice versa,
and this causes build failures on MacOS due to unmatched template
instantiations.
=> use uint{32,64}_t, ul and size_t consistently

.gitignore
A common developer pattern is to symlink this file from a build tree
into a source tree.
=> ignore compile_commands.json

CMakeLists.txt, cmake/Modules/CheckSchedSetAffinity.cmake, libgalois/src/HWTopoLinux.cpp
Previously, the presence of sched_setaffinity was determined by ad-hoc
platform tests. Instead, check for the existence of the function
explicitly. This allows for more generic configuration on unforeseen
platforms like MacOS.
=> check for sched_setaffinity explicitly

libgalois/include/galois/Endian.h
endian.h doesn't exist on MacOS, and we can get all the benefit via
__builtin_bswap{32,64}.
=> remove dependency on endian.h

cmake/Modules/CheckSchedSetAffinity.cmake
This needs to be defined otherwise sched_setaffinity will never be
found.
Tested by:
---
Looks like Arch has updated its boost package
https://www.archlinux.org/packages/?sort=&q=boost&maintainer=&flagged=
(Jan 30), which I think is causing the build failure.
=> Set _GNU_SOURCE when checking for sched_setaffinity

.circleci/config.yml
The newer boost libraries 1.72 on Arch Linux only provide the
multithreaded variants. This causes a CMake configuration failure
because we explicitly set(BOOST_USE_MULTITHREADED OFF).
The most forward looking fix would be to remove the multithreaded
constraint but I'm not sure of the performance implications thereof. For
the time being to unblock the CI, just pin the boost library to a
previous version that does provide non-multithreaded variants.
=> Fix build on Arch Linux

.circleci/config.yml, CMakeLists.txt
The boost multithreaded libraries really only provide very minimal thread safety guarantees and actually are the kinds of thing we want to use, not disable (https://stackoverflow.com/a/20991533/1935144).
=> Use Multithread Enabled Boost

.travis.yml
In anticipation of upcoming release. (Tests will probably fail until the binary packages are public).
=> Add clang 10 to CI

libgalois/CMakeLists.txt, libgalois/include/galois/Timer.h, libgalois/include/galois/runtime/Executor_OnEach.h, libgalois/include/galois/runtime/ThreadTimer.h, libgalois/src/ThreadTimer.cpp, libgalois/src/Timer.cpp
Threads are a low-level primitive and the high-level galois namespace
should probably avoid frequent reference to it. Additionally
PerThreadTimer is (only) used by the runtime. We should minimize
dependencies from the galois::runtime to the galois namespace as ideally
the latter should be expressed in terms of the former rather than the
other way around.
Along the way, I moved as much implementation to the cpp file in an
effort to reduce include dependencies. Previously, Timer.h included both
ctime and chrono. Now it just includes chrono, the standard C++
definition of time.
=> Move PerThreadTimer to galois::runtime

lonestar/SPRoute/CMakeLists.txt, lonestar/aigRewriting/CMakeLists.txt, lonestar/aigRewriting/algorithms/RewriteManager.cpp, lonestar/aigRewriting/functional/FunctionHandler.h, lonestar/aigRewriting/functional/FunctionHandler32.h, lonestar/aigRewriting/parsers/semantic_error.cpp, lonestar/aigRewriting/parsers/semantic_error.h, lonestar/aigRewriting/parsers/syntax_error.cpp, lonestar/aigRewriting/parsers/syntax_error.h, lonestar/aigRewriting/parsers/unexpected_eof.cpp, lonestar/aigRewriting/parsers/unexpected_eof.h, lonestar/matrixcompletion/CMakeLists.txt
This re-enables -Werror for SPRoute and aigRewriting and picks up a miscellaneous fix for the fact that Eigen wasn't getting found properly.
@yishanlu the unused function warnings were actually being caused by having a bunch of functions in headers even though they didn't have inline symbol visiblity. I made all the functions in the offending headers inline as a fix and we now get to have inline variable visibility thanks to C++17 as well, so I used that here too.
=> Build Cleanup

libgalois/include/galois/graphs/LC_CSR_Graph.h, libgalois/include/galois/graphs/ReadGraph.h, lonestar/ktruss/K-Truss.cpp, lonestar/ktruss/Verify.cpp
Code cleaning and porting ktruss + initializing empty edge-data array with unweighted graph.
Tests were done with several input weighted graphs/ unweighted graphs.
BSPCoreThenTruss algo was removed due to its incorrect algorithm.
I was supposed to separate the branch into two, but mistakenly used one. Sorry about that.
=> Code cleaning and porting ktruss + initializing empty edge-data array with unweighted graph

lonestar/eda/cpu/SPRoute/CMakeLists.txt, lonestar/eda/cpu/SPRoute/DataProc.h, lonestar/eda/cpu/SPRoute/main.cpp, lonestar/eda/cpu/SPRoute/maze.h, lonestar/eda/cpu/SPRoute/maze_finegrain.h, lonestar/eda/cpu/SPRoute/maze_lock.h, lonestar/eda/cpu/SPRoute/utility.h
This clears out several (but not all) of the memory leaks found by the address sanitizer. I'm disabling the corresponding test in CI again until we get this to pass with the sanitizers.
=> Additional SPRoute Fixes

libgalois/test/CMakeLists.txt
Without arguments, unit-barriers tests up to the number of threads on
the host machine. This reduces the reproducibility of our test suite.
Instead, set the number of threads to use to a smaller, more modest
number.
Closes #198
=> Remove machine dependence in barrier unit test

.circleci/config.yml, .gitmodules, .travis.yml
The CI won't pass until at least these issues are resolved:
- #195 
- #196 
- #194
(just for historical context, I noticed these errors while discussing #92 though they are not related to that issue itself)
Closes #190
=> ci: Add GPU builds

libgalois/include/galois/config.h.in
This adds macros that can be used to turn off `-Werror` for including external headers. Here's a usage example:
```
GALOIS_ALLOW_WARNINGS
#include "external_header_causing_warnings.hpp"
GALOIS_END_ALLOW_WARNINGS
```
=> Allow Locally Disabling -Werror

libgalois/include/galois/ParallelSTL.h, libgalois/include/galois/graphs/LC_CSR_Graph.h, lonestar/analytics/cpu/triangles/Triangles.cpp
Changed the sorting routine used by triangle counting to be more efficient. Before, it was basically single threaded: more parallelism has been introduced into the procedure.
One thing that may help further is if std::sort parallelism is enabled (if it isn't). GAP is very likely doing so as it enables OpenMP.
https://stackoverflow.com/questions/28520720/c-parallel-sort
This also includes a change to LC_CSR_Graph to expose the local range initialization to allow threads to iterate over a more balanced workload (and required if you want to directly call galois::iterate on an LC_CSR_Graph object).
=> Parallel relabelling for triangle counting

lonestar/analytics/distributed/README.md, lonestar/analytics/distributed/bc/bc_level.cpp, lonestar/analytics/distributed/bc/bc_mr.cpp, lonestar/analytics/distributed/bfs/bfs_pull.cpp, lonestar/analytics/distributed/bfs/bfs_pull_cuda.cu, lonestar/analytics/distributed/bfs/bfs_pull_cuda.h, lonestar/analytics/distributed/bfs/bfs_push.cpp, lonestar/analytics/distributed/bfs/bfs_push_cuda.cu, lonestar/analytics/distributed/bfs/bfs_push_cuda.h, lonestar/analytics/distributed/cc/cc_pull.cpp, lonestar/analytics/distributed/cc/cc_push.cpp, lonestar/analytics/distributed/kcore/kcore_pull.cpp, lonestar/analytics/distributed/kcore/kcore_push.cpp, lonestar/analytics/distributed/pagerank/pagerank_pull.cpp, lonestar/analytics/distributed/pagerank/pagerank_push.cpp, lonestar/analytics/distributed/partition/partition.cpp, lonestar/analytics/distributed/sgd/sgd.cpp, lonestar/analytics/distributed/sssp/sssp_pull.cpp, lonestar/analytics/distributed/sssp/sssp_push.cpp, lonestar/analytics/distributed/tc/tc.cpp, lonestar/libdistbench/CMakeLists.txt, lonestar/libdistbench/include/DistBench/Input.h, lonestar/libdistbench/include/DistBench/MiningStart.h, lonestar/libdistbench/include/DistBench/Output.h, lonestar/libdistbench/include/DistBench/Start.h, lonestar/libdistbench/src/Input.cpp, lonestar/libdistbench/src/Output.cpp, lonestar/libdistbench/src/Start.cpp
Add a command line option to write results `--outputLocation=string`/`--output`.
Downstream, we will be writing these out as parquet files probably, but there is no reason everyone can't benefit from the common extraction code. The output code is outside any timing region so this shouldn't affect benchmark results.
We intend to support remote storage backends like S3, which is why commands do not currently create the output directory if it is missing.
The output API (`writeOutput`) implicitly assumes that node data can just be concatenated together as there is no parameter for indices. We can technically support sparse node data, but as far as I could tell, the current interfaces do not yet expose this functionality (masterNode iterators are just `counting_iterator`s). So, I'm deferring …
=> Structured output

libgalois/CMakeLists.txt, libgalois/include/galois/substrate/HWTopo.h, libgalois/include/galois/substrate/ThreadPool.h, libgalois/src/HWTopo.cpp, libgalois/src/HWTopoDarwin.cpp, libgalois/src/HWTopoLinux.cpp, libgalois/src/ThreadPool.cpp, libgalois/test/hwtopo.cpp
/dev/cpuset may not be mounted in all the environments we run in. In
particular, Docker containers do not mount it. Instead, we can derive
cpuset information from /proc/self/status which always contains the
cpuset information for the current process.
Along the way fix a potential issue where invalid cpuset configurations
would be interpreted as std::vector<int>{0} rather than
std::vector<int>{} due to atoi returning 0 for invalid inputs.
Closes #192
=> Parse cpuset from /proc/self/status

libpangolin/include/pangolin/BfsMining/embedding_list.h, libpangolin/include/pangolin/BfsMining/vertex_miner_api.h, libpangolin/include/pangolin/gtypes.h, libpangolin/include/pangolin/mgraph.h, libpangolin/include/pangolin/miner.h, libpangolin/include/pangolin/util.h, libpangolin/src/BfsMining/embedding_list.cpp, lonestar/mining/cpu/kcl/kcl.cpp, lonestar/mining/cpu/motif/motif.cpp, lonestar/mining/cpu/sgl/sgl.cpp, lonestar/mining/cpu/tc_mine/tc_mine.cpp
Graph is too common a keyword and doesn't tell a user where to
find the declaration. PangolinGraph makes this less of an issue.
Optimally everything in libpangolin should be in a pangolin
namespace; this can be resolved later.
This is in prep for Pangolin-Querying System integration being done elsewhere.
=> Graph in Pangolin -> PangolinGraph

lonestar/mining/cpu/fsm/fsm.cpp, lonestar/mining/cpu/kcl/kcl.cpp, lonestar/mining/cpu/motif/motif.cpp, lonestar/mining/cpu/sgl/sgl.cpp, lonestar/mining/cpu/tc_mine/tc_mine.cpp
For user-controllable parameters, it makes more sense to fail more
visibly when values are invalid rather than using an assertion. The
latter will only report an issue in a debug build.
There seems to be some requirement to not depend on libgalois in the mining code; otherwise, I might have used `GALOIS_ASSERT` and `gError` rather than `printf`. Also there seems to be some confusing naming where the AppMiner parameter is called `ms` (and there is a command line parameter `ms`) while the command line option is `k`. I'm not too familiar with this part of the codebase, so I left things as is.
=> Report error when k argument is invalid

docs/tutorial.dox
- Clarify that this tutorial is for shared memory and does not touch D-Galois.
- Fix dead links like no_conflicts, GSimpleReduce and GBigReduce.
- Structure reorganization:
- Nest **Execution Model** into **Galois Programs** but keep the original order of contents;
- Separate **Graphs** and **Other Data Structures** in **Parallel Data Structures**, as **Concurrent Data Structures** of the manual does.
- Format polishing:
- Extract notes into quote blocks and running examples into dox tables;
- Itemize some text chunks into clearer lists and make the initial word bold of each list items;
- Put csv examples into code blocks.
- Associate sections with corresponding parts in the manual by adding "For details, see <ref-to-man>"s, so that the tutorial acts as a roadmap of the manual.
- Some …
=> Update tutorial docs

.circleci/config.yml, .travis.yml
This should only show a test's command line output if it fails. It will hopefully make it so that the build logs aren't so incredibly huge.
=> Quiet down build logs by only showing output from failed tests.

libgalois/include/galois/FlatMap.h, libgalois/include/galois/ParallelSTL.h, libgalois/include/galois/PerThreadContainer.h, libgalois/include/galois/TwoLevelIterator.h, libgalois/include/galois/graphs/FileGraph.h, libgalois/include/galois/graphs/LC_Morph_Graph.h, libgalois/include/galois/graphs/MorphGraph.h, libgalois/include/galois/graphs/MorphHyperGraph.h, libgalois/include/galois/graphs/Morph_SepInOut_Graph.h, libgalois/include/galois/runtime/Executor_Deterministic.h, libgalois/include/galois/runtime/TiledExecutor.h, libgalois/include/galois/worklists/WorkListHelpers.h, libgalois/test/sort.cpp, lonestar/analytics/cpu/betweennesscentrality/BetweennessCentralityOuter.cpp, lonestar/analytics/cpu/gmetis/Coarsening.cpp, lonestar/analytics/cpu/matrixcompletion/matrixCompletion.cpp, lonestar/analytics/cpu/triangle-counting/Triangles.cpp, lonestar/scientific/cpu/delaunayrefinement/Verifier.h, lonestar/scientific/cpu/delaunaytriangulation/DelaunayTriangulationDet.cpp, lonestar/scientific/cpu/delaunaytriangulation/Graph.h, lonestar/scientific/cpu/delaunaytriangulation/QuadTree.h, lonestar/scientific/cpu/delaunaytriangulation/Verifier.h
They have been removed from the C++17 standard, but as of this commit
libc++ and libstdc++ still provide them, so this is just a
future-proofing measure. It appears that no current functionality relies
on them anyway so they can be removed without any additional
ramifications.
Fixes https://github.com/IntelligentSoftwareSystems/Galois/issues/322.
=> Remove uses of unary_function and binary_function.

.circleci/config.yml, .travis.yml, CMakeLists.txt, README.md, libsupport/CMakeLists.txt, libsupport/include/galois/GetEnv.h, libsupport/include/galois/Logging.h, libsupport/src/GetEnv.cpp, libsupport/src/Logging.cpp, libsupport/test/CMakeLists.txt, libsupport/test/getenv.cpp, libsupport/test/logging.cpp, scripts/docker/Dockerfile
Rebase of https://github.com/KatanaGraph/katana/pull/75 for upstream :heart: 
Biggest design question was the addition of custom formatting for error codes in Logging.h:
https://github.com/IntelligentSoftwareSystems/Galois/pull/325/files#diff-c6650dc73c3e5f6efb29ab8aaf58bdf1R20
It might be a little unexpected that the linking of std::error_code and fmt happens in `Logging.h` but I couldn't think of a better place.
=> Add support library

docs/graphio.dox, libgalois/include/galois/graphs/FileGraph.h, libgalois/include/galois/graphs/OCGraph.h, libgalois/include/galois/substrate/PageAlloc.h, libgalois/src/FileGraph.cpp, libgalois/src/OCFileGraph.cpp, libgalois/src/PageAlloc.cpp, lonestar/analytics/cpu/matching/bipartite-mcm.cpp, lonestar/analytics/cpu/preflowpush/Preflowpush.cpp, tools/graph-convert/graph-convert.cpp, tools/graph-remap/graph-remap.cpp
The current FileGraphWriter does wild memory management: to construct a new graph (from an old graph, e.g. make symmetric, or not), it first builds up `std::vector`s in CSR format, then `memcpy` them to `mmap`'ed space, then reads the data back to the fields inherited from FileGraph, and finally constructs the new graph by the FileGraph. Memory usage is double the size of the new graph, which is bad esp. when the graph is large (in my case, I'm synthesizing regular grids).
I initiated a new FileGraphWriter implementation, namely FileGraphWeaver so that it may co-exist with the old one or replace the old FGW later, which has the same APIs (means least efforts on other code if it replaces the old impl.) but does mmap directly without memcpy.
---
EDIT: The changes are in-place now.
As a …
=> Lower-level FGW w/ careful memory management

libgalois/include/galois/worklists/Obim.h
The == operator actually has higher precedence than the bitwise & operator in C++, so our handling of the BlockPeriod template parameter was actually wrong. This adds clarifying parentheses to get the right result. I'm not yet sure what the performance consequences of this change are.
I noticed this while preparing https://github.com/IntelligentSoftwareSystems/Galois/pull/342. It's a really old bug. I only found it because of a new gcc warning.
=> Fix operator precedence bug in OBIM.

.git-blame-ignore-revs, lonestar/scientific/gpu/barneshut/LICENSE.md, lonestar/scientific/gpu/barneshut/bh.cu, lonestar/scientific/gpu/barneshut/bh_tuning.h
The old Texas State copyright for the GPU version of Barnes Hut was accidentally removed when we relicensed Galois. This restores the copyright. Fortunately the old license for this app was actually already BSD, so we don't have to worry about any additional relicensing issues.
=> Copyright Fixes

libgalois/include/galois/worklists/AdaptiveObim.h
Fixes https://github.com/IntelligentSoftwareSystems/Galois/issues/349, though I'm not entirely sure why yet.
=> Fix assertion failure from erroneous unlock in Adaptive OBIM.

libdist/include/galois/DTerminationDetector.h, libdist/src/DistStats.cpp
Shamelessly stolen from KatanaGraph.
Fixes an issue where host 0 can stay in termination detection because it
detects work after other hosts have decided that they are done with
termination detection.
=> Fix broken barrier in DistStats

CMakeLists.txt, libgpu/include/internal.h
Dist apps such as PageRank may crash on some machines because `multiple_sum` structure elements will contain garbage when default-constructed.
=> Fix 0-initialization of elements in a multiple_sum structure on GPU
